core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

ecommerce_project/urls.py
from ecommerce_project.settings import MEDIA_ROOT, MEDIA_URL
from core import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.list_products, name='list-products'),
]

core/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models


class Product(models.Model):

    name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    is_digital = models.BooleanField(default=True, null=True, blank=True)
    is_available = models.BooleanField(default=True, null=True, blank=True)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

slider/models.py
from django.db import models


class Slider(models.Model):

    title = models.CharField(max_length=100, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='slider/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

core/views.py
from django.shortcuts import render

from slider.models import Slider
from products.models import Product

def index(request):
    sliders = Slider.objects.filter(is_active=True)
    products = Product.objects.filter(is_available=True)[:6]
    context = {
        'sliders': sliders,
        'products':  products,
    }
    return render(request, 'core/index.html', context)


def about(request):
    return render(request, 'core/about.html')

products/views.py
from django.shortcuts import render

from .models import Product

def list_products(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'products/list.html', context)

templates/core/about.html
{% extends 'core/base.html' %} {% block main %}
<section class="container mt-4">
  <div class="row">
    <div class="col-10 mx-auto">
      <div class="jumbotron shadow border">
        <h1 class="text-center">E-Commerce App Developed by Zuber Shekh 👨🏻‍💻</h1>
        <div class="text-center mt-4">
          <a class="btn btn-warning" href="#">Follow on LinkedIn</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock main %}

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ecommerce App</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- NAVBAR -->
    {% include 'partials/navbar.html' %}
    <!-- MAIN -->
    <main class="min-vh-100">{% block main %} {% endblock main %}</main>
    <!-- FOOTER -->
    {% include 'partials/footer.html' %}
    <!-- SCRIPTS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
      integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/core/index.html
{% extends 'core/base.html' %} {% block main %}
<section>
  <div class="row">
    {% if sliders %}
    <div
      id="carouselExampleControls"
      class="carousel slide"
      data-ride="carousel"
    >
      <div class="carousel-inner">
        {% for slider in sliders %}
        <div class="carousel-item {% if forloop.counter0 == 0 %} {{"active"}} {% endif %}">
          <img
            src="{{slider.image.url}}"
            class="d-block w-100"
            alt="{{slider.title}}"
          />
          <div class="carousel-caption d-none d-md-block">
            <h5>{{slider.title}}</h5>
            <p>{{slider.content}}</p>
          </div>
        </div>

        {% endfor %}
      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleControls"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleControls"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    {% endif %}
  </div>
  <div class="container">
    <div class="row mt-4">
      <div class="col-10 mx-auto">
        <div class="jumbotron shadow border">
          <h1 class="text-center">Welcome to Ecommerce App 🙏🏼</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mt-4">
        <h2 class="d-block w-100 text-center mb-4">Best Products</h2>
        {% for product in products %}
          <div class="col-md-4">
            <div class="card shadow">
              <img src="{{product.image.url}}" alt="{{product.name}}" class="card-img-top">
              <div class="card-body">
                <h3>{{product.name}}</h3>
                <p class="lead">{{product.description|truncatechars:30}}</p>
                <h5>$ {{product.price|floatformat:2}}/- Only</h5>
                <div class="text-center mt-3">
                  <a class="btn btn-block btn-primary" href="">Buy Now</a>
                </div>
              </div>
              
            </div>
          </div>
        {% endfor %}
    </div>
  </div>
</section>
{% endblock main %}

templates/partials/footer.html
<footer class="container-fluid bg-dark text-light mt-4">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="py-4">
        <h4 class="text-center">&copy; Copyright &commat; Zuber Shekh</h4>
      </div>
    </div>
  </div>
</footer>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light py-4 shadow">
  <a class="navbar-brand" href="#">Ecommerce</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'products:list-products' %}"
          >Explore</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:about' %}">About</a>
      </li>
    </ul>
  </div>
</nav>

templates/products/list.html
{% extends 'core/base.html' %} {% block main %}
<section class="container mt-4">
  <div class="row">
    <div class="container">
      <h1 class="text-center">Products</h1>
      <hr />
    </div>
    {% for product in products %}
    <div class="col-4 mt-2">
      <img
        class="card-img-top"
        src="{{product.image.url}}"
        alt="{{product.name}}"
      />
      <div class="card">
        <div class="card-body">
          <h3>{{product.name}}</h3>
          <p class="lead">{{product.description|truncatechars:30}}</p>
          <h5>$ {{product.price|floatformat:2}}/- Only</h5>
          <div class="text-center mt-3">
            <a class="btn btn-block btn-info" href="">Add to Cart</a>
            <a class="btn btn-block btn-primary" href="">Buy Now</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock main %}